/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package readisapp;


import javax.swing.*;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;



/**
 *
 * @author NUR
 */
public class BooksFrame extends javax.swing.JFrame {
    
public static BooksFrame bookFrameInstance;
public static BooksFrame getInstance() {
    if (bookFrameInstance == null) {
        // create but don't show immediately
        bookFrameInstance = new BooksFrame();
    }
    return bookFrameInstance;
}

private JPanel[] panels;
private JTextField [] titles;
private int bookCount = 0;
        
        
    public BooksFrame() {
        initComponents();
        loadBooks();
        
        panels = new JPanel[]{panelBook1,panelBook3,panelBook4,panelBook2,panelBook5,panelBook6};
        titles = new JTextField[]{};
        bookFrameInstance = this;
        
        booksGrid.setLayout(new FlowLayout(FlowLayout.LEFT, 15, 15));

        loadBooks();
    }

private void loadBooks() {
    try {
        Connection conn = Database.getConnection();
        String sql = "SELECT id_buku, judul FROM buku LIMIT 6";
        PreparedStatement ps = conn.prepareStatement(sql);
        ResultSet rs = ps.executeQuery();

        bookCount = 0; // reset
        while (rs.next() && bookCount < panels.length) {
            String cover = rs.getString("cover");
            String file = rs.getString("file");
            String judul = rs.getString("judul");
            String penulis = rs.getString("penulis");
            String genre = rs.getString("genre");
            String sinopsis = rs.getString("sinopsis");

            addBook(cover, file, judul, penulis, genre, sinopsis);
        }

    } catch (Exception e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, "Gagal memuat buku!");
    }
}

public void addBook(String cover, String file, String judul, String penulis, String genre, String sinopsis) {

    JPanel slot = panels[bookCount];
    slot.removeAll();
    slot.setLayout(new BorderLayout());

    // Cover
    JLabel lblCover = new JLabel();
    lblCover.setHorizontalAlignment(SwingConstants.CENTER);

    ImageIcon icon = new ImageIcon(
        new ImageIcon(cover).getImage().getScaledInstance(
            90, 123, Image.SCALE_SMOOTH
        )
    );
    lblCover.setIcon(icon);

    // Tombol detail
       JButton btnDetail = new JButton(judul);
    btnDetail.addActionListener(e -> {
    SinopsisFrame.getInstance().setData(judul, penulis, genre, sinopsis, cover, file);
    SinopsisFrame.getInstance().setVisible(true);
    });

    slot.add(lblCover, BorderLayout.CENTER);
    slot.add(btnDetail, BorderLayout.SOUTH);

    slot.revalidate();
    slot.repaint();

    bookCount++;
    
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel6 = new javax.swing.JPanel();
        books = new javax.swing.JButton();
        favorite = new javax.swing.JButton();
        genreBtn = new javax.swing.JButton();
        labelTitle = new java.awt.Label();
        searchField = new javax.swing.JTextField();
        mainPanel = new javax.swing.JPanel();
        btnHome = new javax.swing.JButton();
        btnFavorite = new javax.swing.JButton();
        btnGenre = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        booksGrid = new javax.swing.JPanel();
        panelBook1 = new javax.swing.JPanel();
        panelBook2 = new javax.swing.JPanel();
        panelBook3 = new javax.swing.JPanel();
        panelBook4 = new javax.swing.JPanel();
        panelBook5 = new javax.swing.JPanel();
        panelBook6 = new javax.swing.JPanel();

        jPanel6.setBackground(new java.awt.Color(153, 153, 153));

        books.setText("Home");
        books.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                booksActionPerformed(evt);
            }
        });

        favorite.setText("Favorite");
        favorite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                favoriteActionPerformed(evt);
            }
        });

        genreBtn.setText("Genre");
        genreBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                genreBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(books, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(favorite, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(genreBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(books)
                .addGap(37, 37, 37)
                .addComponent(favorite)
                .addGap(36, 36, 36)
                .addComponent(genreBtn)
                .addContainerGap(142, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(501, 409));

        labelTitle.setBackground(new java.awt.Color(77, 72, 219));
        labelTitle.setFont(new java.awt.Font("Dialog", 0, 50)); // NOI18N
        labelTitle.setText("Readis");

        searchField.setText("Search");
        searchField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchFieldActionPerformed(evt);
            }
        });

        mainPanel.setBackground(new java.awt.Color(153, 153, 153));

        btnHome.setText("Home");
        btnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeActionPerformed(evt);
            }
        });

        btnFavorite.setText("Favorite");
        btnFavorite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFavoriteActionPerformed(evt);
            }
        });

        btnGenre.setText("Genre");
        btnGenre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenreActionPerformed(evt);
            }
        });

        jButton7.setText("Tambah");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnHome, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jButton7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnFavorite, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnGenre, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(btnHome)
                .addGap(37, 37, 37)
                .addComponent(btnFavorite)
                .addGap(36, 36, 36)
                .addComponent(btnGenre)
                .addGap(36, 36, 36)
                .addComponent(jButton7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        java.awt.FlowLayout flowLayout1 = new java.awt.FlowLayout();
        flowLayout1.setAlignOnBaseline(true);
        booksGrid.setLayout(flowLayout1);

        panelBook1.setBackground(new java.awt.Color(102, 102, 102));
        panelBook1.setPreferredSize(new java.awt.Dimension(90, 123));

        javax.swing.GroupLayout panelBook1Layout = new javax.swing.GroupLayout(panelBook1);
        panelBook1.setLayout(panelBook1Layout);
        panelBook1Layout.setHorizontalGroup(
            panelBook1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 90, Short.MAX_VALUE)
        );
        panelBook1Layout.setVerticalGroup(
            panelBook1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 123, Short.MAX_VALUE)
        );

        booksGrid.add(panelBook1);

        panelBook2.setBackground(new java.awt.Color(102, 102, 102));
        panelBook2.setPreferredSize(new java.awt.Dimension(90, 125));

        javax.swing.GroupLayout panelBook2Layout = new javax.swing.GroupLayout(panelBook2);
        panelBook2.setLayout(panelBook2Layout);
        panelBook2Layout.setHorizontalGroup(
            panelBook2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 90, Short.MAX_VALUE)
        );
        panelBook2Layout.setVerticalGroup(
            panelBook2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 125, Short.MAX_VALUE)
        );

        booksGrid.add(panelBook2);

        panelBook3.setBackground(new java.awt.Color(102, 102, 102));
        panelBook3.setPreferredSize(new java.awt.Dimension(90, 123));

        javax.swing.GroupLayout panelBook3Layout = new javax.swing.GroupLayout(panelBook3);
        panelBook3.setLayout(panelBook3Layout);
        panelBook3Layout.setHorizontalGroup(
            panelBook3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 90, Short.MAX_VALUE)
        );
        panelBook3Layout.setVerticalGroup(
            panelBook3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 123, Short.MAX_VALUE)
        );

        booksGrid.add(panelBook3);

        panelBook4.setBackground(new java.awt.Color(102, 102, 102));
        panelBook4.setPreferredSize(new java.awt.Dimension(90, 123));

        javax.swing.GroupLayout panelBook4Layout = new javax.swing.GroupLayout(panelBook4);
        panelBook4.setLayout(panelBook4Layout);
        panelBook4Layout.setHorizontalGroup(
            panelBook4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 90, Short.MAX_VALUE)
        );
        panelBook4Layout.setVerticalGroup(
            panelBook4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 123, Short.MAX_VALUE)
        );

        booksGrid.add(panelBook4);

        panelBook5.setBackground(new java.awt.Color(102, 102, 102));
        panelBook5.setPreferredSize(new java.awt.Dimension(90, 125));

        javax.swing.GroupLayout panelBook5Layout = new javax.swing.GroupLayout(panelBook5);
        panelBook5.setLayout(panelBook5Layout);
        panelBook5Layout.setHorizontalGroup(
            panelBook5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 90, Short.MAX_VALUE)
        );
        panelBook5Layout.setVerticalGroup(
            panelBook5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 125, Short.MAX_VALUE)
        );

        booksGrid.add(panelBook5);

        panelBook6.setBackground(new java.awt.Color(102, 102, 102));
        panelBook6.setPreferredSize(new java.awt.Dimension(90, 125));

        javax.swing.GroupLayout panelBook6Layout = new javax.swing.GroupLayout(panelBook6);
        panelBook6.setLayout(panelBook6Layout);
        panelBook6Layout.setHorizontalGroup(
            panelBook6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 90, Short.MAX_VALUE)
        );
        panelBook6Layout.setVerticalGroup(
            panelBook6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 125, Short.MAX_VALUE)
        );

        booksGrid.add(panelBook6);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelTitle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 490, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(booksGrid, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addComponent(searchField))
                .addGap(10, 10, 10))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(labelTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(searchField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(booksGrid, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 440, Short.MAX_VALUE)
                    .addComponent(mainPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void booksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_booksActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_booksActionPerformed

    private void favoriteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_favoriteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_favoriteActionPerformed

    private void genreBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_genreBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_genreBtnActionPerformed

    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnHomeActionPerformed

    private void btnFavoriteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFavoriteActionPerformed
        new FavoriteFrame().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnFavoriteActionPerformed

    private void btnGenreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenreActionPerformed
        new GenreFrame().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnGenreActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        new TambahBukuFrame().setVisible(true);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void searchFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BooksFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BooksFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BooksFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BooksFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                BooksFrame.getInstance().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton books;
    private javax.swing.JPanel booksGrid;
    private javax.swing.JButton btnFavorite;
    private javax.swing.JButton btnGenre;
    private javax.swing.JButton btnHome;
    private javax.swing.JButton favorite;
    private javax.swing.JButton genreBtn;
    private javax.swing.JButton jButton7;
    private javax.swing.JPanel jPanel6;
    private java.awt.Label labelTitle;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPanel panelBook1;
    private javax.swing.JPanel panelBook2;
    private javax.swing.JPanel panelBook3;
    private javax.swing.JPanel panelBook4;
    private javax.swing.JPanel panelBook5;
    private javax.swing.JPanel panelBook6;
    private javax.swing.JTextField searchField;
    // End of variables declaration//GEN-END:variables
}
